apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileuploader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileuploader
  template:
    metadata:
      labels:
        app: fileuploader
    spec:
      containers:
        - name: fileuploader-container
          image: fileuploader.azurecr.io/fileloader:latest
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: OPENAI_API_KEY
          - name: OPENAI_API_TYPE
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: OPENAI_API_TYPE
          - name: OPENAI_API_VERSION
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: OPENAI_API_VERSION
          - name: OPENAI_API_BASE
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: OPENAI_API_BASE
          - name: BLOBNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: BLOBNAME
          - name: BLOBKEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: BLOBKEY
          - name: DEEPL_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DEEPL_API_KEY
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SERVER_URL
          - name: TRANSLATOR_SUBSCRIPTION_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: TRANSLATOR_SUBSCRIPTION_KEY
          - name: WEBPUBSUB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: WEBPUBSUB_ENDPOINT
          - name: WEBPUBSUB_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: WEBPUBSUB_KEY
          - name: VECTOR_STORE_ADDRESS
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: VECTOR_STORE_ADDRESS
          - name: VECTOR_STORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: VECTOR_STORE_PASSWORD
          ports:
            - containerPort: 8080
