apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-pro
  namespace: fileuploader-service
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dev@foundation29.org
    privateKeySecretRef:
      name: letsencrypt-pro
    solvers:
    - http01:
        ingress:
          class: nginx
