apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  OPENAI_API_KEY: c2stV3FnS2s4RFhDdmwzWThkT0JFMzVUM0JsYmtGSmRqUXBkMDBocFNtV2hEWXhFMFFD
  PINECONE_API_KEY: ZmZkNzU2MWItMmQ1OC00YTU0LThlOTAtOTY3ODk4NjY5YjVh
  PINECONE_ENVIRONMENT: ZXUtd2VzdDEtZ2Nw
  BLOBNAME: YmxvYnJhaXRvZ3B0MmRldg==
  BLOBKEY: Mkg5NmJDb1dmNFp0QlRNSzNBQytoRUsrWmNOLzhBbVcwc0hSNzdBSkNqb2Jqa1lPY2xlSFRWWWVHWVE5Z1doc2o1ejlleFZ5b0UwbitBU3RHcDRhSlE9PQ==
  DEEPL_API_KEY: Yjk3ZWVmMmQtNDczYi1hYzcyLWEzNTUtMDUyZjUzODkyYjk4
