apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  OPENAI_API_KEY: MGNiZmVmMWJhYjdlNDA0M2IzY2UzZDM0YWNiOWVmOTM=
  OPENAI_API_TYPE: YXp1cmU=
  OPENAI_API_VERSION: MjAyMy0wNi0wMS1wcmV2aWV3
  OPENAI_API_BASE: aHR0cHM6Ly9uYXYyOS5vcGVuYWkuYXp1cmUuY29tLw==
  BLOBNAME: YmxvYnJhaXRvZ3B0Mg==
  BLOBKEY: RW9BTnN6aS9Vdmk0UHBiSDNWRXhoOUh4R3ZWSlg5Sk5FY1FrVzV2aytRdmVndVRBLzNWY05RZlMzWjFaekFMNzIwd3VZVWM4eEY2UitBU3RPNDhHT0E9PQ==
  DEEPL_API_KEY: Yjk3ZWVmMmQtNDczYi1hYzcyLWEzNTUtMDUyZjUzODkyYjk4
  SERVER_URL: aHR0cHM6Ly9uYXYyOS5vcmc=
  TRANSLATOR_SUBSCRIPTION_KEY: MzAyYjQxMmZkZWM1NGY4NTk1YjMwNzVjNGU2MTA3NTQ=
  WEBPUBSUB_ENDPOINT: aHR0cHM6Ly9yYWl0by53ZWJwdWJzdWIuYXp1cmUuY29t
  WEBPUBSUB_KEY: T1ZGZHZ4WURpV1NCYlF2MDNlVnZxN1AveXU1dTUvcGw3VFlKMHBGczNhYz0=
  VECTOR_STORE_ADDRESS: aHR0cHM6Ly9uYXYyOWNvZ3NlYXJjaC5zZWFyY2gud2luZG93cy5uZXQ=
  VECTOR_STORE_PASSWORD: QTJncXUyQVJveXROcWJMcllBTFRYT2ZDTlMxOFJMODk0ZWJEeDZpSGhWQXpTZUR4bG5lMQ==
