apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  OPENAI_API_KEY: c2stV3FnS2s4RFhDdmwzWThkT0JFMzVUM0JsYmtGSmRqUXBkMDBocFNtV2hEWXhFMFFD
  PINECONE_API_KEY: MzAxOTExZmEtMjc5NS00NjIwLTk5OTgtYWEyNGRkYWI1Zjhl
  PINECONE_ENVIRONMENT: ZXUtd2VzdDEtZ2Nw
  BLOBNAME: YmxvYnJhaXRvZ3B0Mg==
  BLOBKEY: RW9BTnN6aS9Vdmk0UHBiSDNWRXhoOUh4R3ZWSlg5Sk5FY1FrVzV2aytRdmVndVRBLzNWY05RZlMzWjFaekFMNzIwd3VZVWM4eEY2UitBU3RPNDhHT0E9PQ==
  DEEPL_API_KEY: Yjk3ZWVmMmQtNDczYi1hYzcyLWEzNTUtMDUyZjUzODkyYjk4
